### ISSUE TITLE
ミュート設定が適用されない

### ISSUE THREAD

**Issue by acid-chicken** [come25136/OZtter#4]
# 問題点

Twitter上で設定されているミュート機能がOZtterではうまく適用されていない。

**Comment by ghost** [comment]
[https://gist.github.com/nukosama/884fad6cf1335d7d9aa8e010dda00b24](https://gist.github.com/nukosama/884fad6cf1335d7d9aa8e010dda00b24)

こんな感じでいかがでしょう
