### ISSUE TITLE
サイトアクセス時にAuth画面に常に飛ばされる

### ISSUE THREAD

**Issue by acid-chicken** [come25136/OZtter#5]
# 問題点

 [oztter.f5.si](oztter.f5.si) にアクセスすると、認証状態にかかわらずTwitterのAuth画面に飛ばされ、利便性の低下がみられる。
# 改善点

認証済みの場合は [oztter.f5.si/login.php](oztter.f5.si/login.php) にジャンプするべきである。

**Comment by come25136** [comment]
PHP configの問題なので、このlssuesはクローズさせていただきます
